Add styling
Balikuddembe/-Leaderboard-list-app pull request #3
Opened 2022-11-18 19:10 UTC by Balikuddembe

Hi 👋 ,In this PR,I added styling of my choice to this project to add more feel and look.

2022-11-18 19:17 UTC, Qoosim reviewed
#   *Status: Invalidated* :red_circle: 

Hi @Balikuddembe, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that `has no linter set up. Kindly set up the proper linter files for your project.`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-18 20:31 UTC, ShahierNashaat requested changes
Hi @Balikuddembe, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Your code is clean and well documented ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-18 20:31 UTC, ShahierNashaat commented on src/style.css
> +}
- [ ] Kindly notice that the table is showing the scores out of the container, and that making it not like the wireframe please fix that.
- [ ] Also there is a horizontal scroll please fix that too.

Your Design | Wireframe
------------- | ----------------
![Capture](https://user-images.githubusercontent.com/33752735/202796588-f23a9441-d7a7-487c-81ce-d3a74311b3fb.PNG) | ![image](https://user-images.githubusercontent.com/33752735/202796679-75a50237-cc55-4d4f-86a5-3b56749c243d.png)

2022-11-19 08:40 UTC, Wes-Isaac approved these changes
Hi @Balikuddembe,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Correct use of GitFlow 👍
- Descriptive commit messages 💯
- Professional looking pull request 🥇 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-19 09:00 UTC, merged